from rest_framework import routers
from . import views as myapp_views

router = routers.DefaultRouter()
router.register(r'users', myapp_views.UserViewset)
router.register(r'Country', myapp_views.CountryViewset)
router.register(r'City', myapp_views.CityViewset)
router.register(r'Genre', myapp_views.GenreViewset)
router.register(r'Cast', myapp_views.CastViewset)
router.register(r'ArticleCategory', myapp_views.ArticleCategoryViewset)
router.register(r'Tag', myapp_views.TagViewset)
router.register(r'Movie', myapp_views.MovieViewset)
router.register(r'MovieGenre', myapp_views.MovieGenreViewset)
router.register(r'MoviePoster', myapp_views.MoviePosterViewset)
router.register(r'MovieTrailer', myapp_views.MovieTrailerViewset)
router.register(r'Actor', myapp_views.ActorViewset)
router.register(r'ActorMoviePoster', myapp_views.ActorMoviePosterViewset)
router.register(r'ActorMovieTrailer', myapp_views.ActorMovieTrailerViewset)
router.register(r'Comment', myapp_views.CommentViewset)
router.register(r'MovieComment', myapp_views.MovieCommentViewset)
router.register(r'Review', myapp_views.ReviewViewset)
router.register(r'MovieReview', myapp_views.MovieReviewViewset)
router.register(r'MovieCast', myapp_views.MovieCastViewset)
router.register(r'Series', myapp_views.SeriesViewset)
router.register(r'Season', myapp_views.SeasonViewset)
router.register(r'Episode', myapp_views.EpisodeViewset)
router.register(r'SeriesGenre', myapp_views.SeriesGenreViewset)
router.register(r'SeriesPoster', myapp_views.SeriesPosterViewset)
router.register(r'SeriesTrailer', myapp_views.SeriesTrailerViewset)
router.register(r'SeriesComment', myapp_views.SeriesCommentViewset)
router.register(r'SeriesCast', myapp_views.SeriesCastViewset)
router.register(r'SeriesReview', myapp_views.SeriesReviewViewset)
router.register(r'Article', myapp_views.ArticleViewset)
router.register(r'ArticleTag', myapp_views.ArticleTagViewset)
router.register(r'ArticleComment', myapp_views.ArticleCommentViewset)
router.register(r'UserFavorite', myapp_views.UserFavoriteViewset)
router.register(r'UserRate', myapp_views.UserRateViewset)


# router.register(r'relativeTypes', myapp_views.RelativeTypeViewset)
# router.register(r'patientProfiles', myapp_views.PatientProfileViewset)
